#!/bin/sh -e

set -e

# ref: postinst in sudo package

case "$1" in
purge)
  ;;

remove)
  ;;

upgrade | deconfigure)
  #
  ;;

abort-upgrade | failed-upgrade)
  ;;

*)
  echo "unknown argument --> $1" >&2
  exit 0
  ;;

esac
